# Generated by Django 5.0.7 on 2024-07-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("services", models.TextField()),
                ("date_booked", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
